spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6adtq0wb9xprpb4.mysql.rds.aliyuncs.com:3306/xm1?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: 1076094242mM
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    port: 5672
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-prefix: mall_


#server:
#  servlet:
#    session:
#      timeout: 30M #默认值








